/**
 * DESIGN.md frontmatter 토큰을 전부 등록한다.
 * 화면 HTML(code.html)들이 bg-primary / text-text-muted / font-headline-lg-mobile 등
 * 토큰 클래스를 그대로 사용하므로 여기 등록되어 있어야 렌더링이 일치한다.
 *
 * [자율결정] borderRadius: DESIGN.md frontmatter의 `rounded` 스케일(xl=1.5rem 등)과
 *   화면 HTML tailwind.config(xl=0.75rem)이 충돌한다. 화면(screen.png)과의 시각적 일치가
 *   완료 기준이고, DESIGN.md "Shapes" 산문(버튼/입력 12px = 0.75rem)도 화면 값과 일치하므로
 *   화면 HTML 값(xl=0.75rem)을 채택. rounded-2xl/3xl은 Tailwind 기본값(1rem/1.5rem) 유지.
 */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#464555',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#777587',
        'outline-variant': '#c7c4d8',
        'surface-tint': '#4d44e3',
        primary: '#3525cd',
        'on-primary': '#ffffff',
        'primary-container': '#4f46e5',
        'on-primary-container': '#dad7ff',
        'inverse-primary': '#c3c0ff',
        secondary: '#006c49',
        'on-secondary': '#ffffff',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        tertiary: '#684000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#885500',
        'on-tertiary-container': '#ffd4a4',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e2dfff',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary-fixed': '#0f0069',
        'on-primary-fixed-variant': '#3323cc',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        'surface-variant': '#d3e4fe',
        'bg-primary': '#FFFFFF',
        'bg-secondary': '#F8FAFC',
        'surface-border': '#E2E8F0',
        'text-main': '#0F172A',
        'text-muted': '#64748B',
        'vault-blur': 'rgba(255, 255, 255, 0.4)',
      },
      fontFamily: {
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-sm': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        caption: ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'base-unit': '4px',
        'container-padding': '20px',
        'stack-gap-sm': '8px',
        'stack-gap-md': '16px',
        'stack-gap-lg': '24px',
        'grid-gutter': '12px',
      },
    },
  },
  plugins: [],
};
